  export const ATTR_CONTEXT = 'context'
  export const ATTR_Q_FRONT = 'qFront'
  export const ATTR_Q_CURRENT = 'qCurrent'
  export const ATTR_STATE = 'state'
  export const ATTR_WAS_PIN_ENTERED = 'wasPINEntered'
  export const ATTR_RECIPE = "recipe"

  export const FIRST_NAME = 'Addison'
  export const LAUNCH_REQUEST = 'LaunchRequest'
  export const INTENT_REQUEST = 'IntentRequest'
  export const YES_INTENT = 'AMAZON.YesIntent'
  export const NO_INTENT = 'AMAZON.NoIntent'
  export const PIN_INTENT = 'PinIntent'
  export const RECIPE_INTENT = 'RecipeIntent'
  export const NOTIFICATIONS_INTENT = 'NotificationsIntent'

  export const STATE_NULL = ''
  export const STATE_WAITING_FOR_PIN = 'WaitingForPin'
  export const STATE_SET_APPT_REMINDER = 'SetApptReminder?'
  export const STATE_ORDER_REFILL = 'OrderRefill?'
  export const STATE_HEAR_MORE_ABOUT_MAIL_ORDER = 'HearMoreAboutMailOrder?'
  export const STATE_CREATE_PICKUP_SCRIP_REMINDER = 'CreatePickupScripReminder?'
  export const STATE_CREATE_TAKE_SCRIPT_REMINDER = 'CreateTakeScripReminder?'
  export const STATE_HEAR_NEXT_NOTIFICATION = 'HearNextNotification?'
  export const STATE_HEAR_RECIPE = 'HearRecipe?'
