"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ATTR_CONTEXT = 'context';
exports.ATTR_Q_FRONT = 'qFront';
exports.ATTR_Q_CURRENT = 'qCurrent';
exports.ATTR_STATE = 'state';
exports.ATTR_WAS_PIN_ENTERED = 'wasPINEntered';
exports.ATTR_RECIPE = "recipe";
exports.NAME = 'Addison';
exports.LAUNCH_REQUEST = 'LaunchRequest';
exports.INTENT_REQUEST = 'IntentRequest';
exports.YES_INTENT = 'AMAZON.YesIntent';
exports.NO_INTENT = 'AMAZON.NoIntent';
exports.PIN_INTENT = 'PinIntent';
exports.RECIPE_INTENT = 'RecipeIntent';
exports.NOTIFICATIONS_INTENT = 'NotificationsIntent';
exports.STATE_NULL = '';
exports.STATE_WAITING_FOR_PIN = 'WaitingForPin';
exports.STATE_SET_APPT_REMINDER = 'SetApptReminder?';
exports.STATE_ORDER_REFILL = 'OrderRefill?';
exports.STATE_HEAR_MORE_ABOUT_MAIL_ORDER = 'HearMoreAboutMailOrder?';
exports.STATE_CREATE_PICKUP_SCRIP_REMINDER = 'CreatePickupScripReminder?';
exports.STATE_CREATE_TAKE_SCRIPT_REMINDER = 'CreateTakeScripReminder?';
exports.STATE_HEAR_NEXT_NOTIFICATION = 'HearNextNotification?';
exports.STATE_HEAR_RECIPE = 'HearRecipe?';
